"""
Jira模块 → 业务领域 映射表
来源：jira模块对应业务领域.xlsx → 模块对应 sheet
"""
MODULE_TO_DOMAIN = {
    "(Drv) Audio": "音视频",
    "(Drv) Audio_tOS": "音视频",
    "(Drv) Charger": "续航温升",
    "(Drv) Charger, LowPower": "续航温升",
    "(Drv) Fingerprint": "器件",
    "(Drv) KE&HW reboot": "稳定性",
    "(Drv) LCM": "器件",
    "(Drv) LED": "系统应用",
    "(Drv) Modem": "通信",
    "(Drv) OTG": "器件",
    "(Drv) Sensor-ACC&G": "器件",
    "(Drv) Sensor-ALS": "器件",
    "(Drv) Sensor-IRTX": "器件",
    "(Drv) Sensor-MAG": "器件",
    "(Drv) Sensor-PS": "器件",
    "(Drv) Sensor-PS(Ultrasonic)": "器件",
    "(Drv) TP": "器件",
    "(Drv) Vibrator": "音视频",
    "(Drv) Video Codec": "音视频",
    "(Drv)Security": "系统特性",
    "3RD Application": "三方",
    "3RD Application, 3RD_Games": "三方",
    "3RD Application, 3RD_IM&Social": "三方",
    "3RD Application, 3RD_LocalLife": "三方",
    "3RD Application, 3RD_NewApps": "三方",
    "3RD_Entertainment": "三方",
    "3RD_Entertainment_tOS": "三方",
    "3RD_Entertainment_tOS,3rdCommon": "三方",
    "3RD_Entertainment_tOS, 3rdCommon": "三方",
    "3RD_Games": "三方",
    "3RD_Games_tOS": "三方",
    "3RD_Games_tOS, 3rdCommon": "三方",
    "3RD_Games_tOS,3rdCommon": "三方",
    "3RD_IM&Social": "三方",
    "3RD_IM&Social_tOS": "三方",
    "3RD_IM&Social_tOS, 3rdCommon": "三方",
    "3RD_IM&Social_tOS,3rdCommon": "三方",
    "3RD_LocalLife": "三方",
    "3RD_LocalLife_tOS": "三方",
    "3RD_LocalLife_tOS, 3rdCommon": "三方",
    "3RD_LocalLife_tOS,3rdCommon": "三方",
    "3RD_NewApps": "三方",
    "3RD_NewApps_tOS": "三方",
    "3RD_NewApps_tOS, 3rdCommon": "三方",
    "3RD_NewApps_tOS,3rdCommon": "三方",
    "3RD_News&Books_tOS": "三方",
    "3RD_News&Books_tOS,3rdCommon": "三方",
    "3RD_News&Books_tOS, 3rdCommon": "三方",
    "3RD_Tools&Browser": "三方",
    "3RD_Tools&Browser_tOS": "三方",
    "3RD_Tools&Browser_tOS, Google APPS_tOS": "三方",
    "3RD_Tools&Browser_tOS, 3rdCommon": "三方",
    "3RD_Tools&Browser_tOS,3rdCommon": "三方",
    "3RD_Travel&Navigation_tOS": "三方",
    "3RD_Travel&Navigation_tOS, 3rdCommon": "三方",
    "3RD_Travel&Navigation_tOS,Google APPS_tOS": "三方",
    "3rdCommon": "三方",
    "3rdCommon, DataPerformance": "三方",
    "3rdCommon, DynamicBar": "三方",
    "3rdCommon, Facemoji": "三方",
    "3rdCommon, FontManager": "三方",
    "3rdCommon, Framework_Display": "三方",
    "3rdCommon, Framework_other": "三方",
    "3rdCommon, GameSpace": "三方",
    "3rdCommon, Google APPS_tOS": "三方",
    "3rdCommon, MOL": "三方",
    "3rdCommon, NFC-Settings": "三方",
    "3rdCommon, NavigationBar": "三方",
    "3rdCommon, Network": "三方",
    "3rdCommon, Notes": "三方",
    "3rdCommon, Notification": "三方",
    "3rdCommon, PalmStore": "三方",
    "3rdCommon, Questionnaire": "三方",
    "3rdCommon, RecentAPP": "三方",
    "3rdCommon, Settings": "三方",
    "3rdCommon, ShareVia": "三方",
    "3rdCommon, SplitScreen": "三方",
    "3rdCommon, ThunderBack": "三方",
    "3rdCommon, UI_UX_UE": "三方",
    "3rdCommon, Video Codec": "三方",
    "3rdCommon, WIFI-Settings": "三方",
    "3rdCommon, AICoreModelManager": "三方",
    "3rdCommon, MobileCloner": "三方",
    "3rdCommon, Questionnaire": "三方",
    "AICoreLLM": "基础服务",
    "AICoreModelManager": "基础服务",
    "AICoreService": "基础服务",
    "AIGallery": "敏捷测试",
    "AIGalleryOS": "敏捷测试",
    "AIWallpaper": "桌面产品",
    "AIZeroScreen": "桌面产品",
    "AMS/WMS、Main Screen Display": "框架应用",
    "AOD": "门户产品",
    "APN": "通信",
    "APPLock": "系统应用",
    "AskAI": "框架应用",
    "AudioLink": "AIOT",
    "Battery Lab": "续航温升",
    "Bluetooth": "AIOT",
    "Bluetooth-Settings": "AIOT",
    "Boomplay": "三方",
    "Calculator": "创新产品",
    "Calendar": "创新产品",
    "CallFuction": "通信",
    "CallPerformance": "通信",
    "Camera 3RD": "影像功能",
    "Camera APP": "影像功能",
    "Camera Driver": "影像功能",
    "Camera Effect": "影像评测",
    "Camera Experience": "影像功能",
    "Camera IQ": "影像功能",
    "Carlcare": "三方",
    "Charginganimation": "门户产品",
    "Childmode": "系统应用",
    "Clipper": "敏捷测试",
    "Clipper-Oneshot": "敏捷测试",
    "Clock": "创新产品",
    "CloudFolder": "桌面产品",
    "Compass": "创新产品",
    "Contact": "通信",
    "CutePet": "桌面产品",
    "DataFunction": "通信",
    "DataPerformance": "通信",
    "DataPerformance-PD": "通信",
    "DemoMode": "基础服务",
    "Dialer": "通信",
    "DragDrop": "框架应用",
    "DualApp/App twin/XClone": "系统应用",
    "Dynamic Color": "框架应用",
    "DynamicBar": "门户产品",
    "Easypic": "敏捷测试",
    "Effect_Camera": "影像评测",
    "Ella": "基础服务",
    "Ella识屏": "基础服务",
    "Energy": "基础服务",
    "Ewarrantycard": "基础服务",
    "FMRadio": "敏捷测试",
    "FW_DualSystem": "系统应用",
    "FaceUnlock": "影像功能",
    "Facemoji": "三方",
    "Feedback": "基础服务",
    "FileManager": "创新产品",
    "Finder": "基础服务",
    "Flipmusic": "敏捷测试",
    "Foldable_compatibility": "框架应用",
    "Foldable_display": "框架应用",
    "Font": "框架应用",
    "FontManager": "框架应用",
    "Framework": "系统应用",
    "Framework_Display": "框架应用",
    "Framework_Fingerprint": "器件",
    "Framework_other": "框架应用",
    "GMS": "GMS",
    "GPS-HW": "AIOT",
    "GPS-SW": "AIOT",
    "GameMode": "游戏",
    "GameSpace": "游戏",
    "Gesture Navigation": "门户产品",
    "GlobalSearch": "桌面产品",
    "GlobalTheme": "桌面产品",
    "Google APPS_tOS": "GMS",
    "Google Apps": "系统应用",
    "Grffin": "性能",
    "HIOSLauncher": "桌面产品",
    "HW-Audio-HW": "音视频",
    "HW-Power-HW": "基带",
    "HW-Thermal-SW": "续航温升",
    "HW-Thermel-HW": "续航温升",
    "HW-Thermel-SW": "续航温升",
    "Health": "AIOT",
    "Heavy Loading Performance": "性能",
    "Hi Translate": "三方",
    "Hoffnung": "基础服务",
    "Hola Browser": "三方",
    "Ims_volte_vowifi": "通信",
    "ItelLauncher": "桌面产品",
    "Itle Launcher": "桌面产品",
    "LCM_Effect": "器件",
    "LED": "系统应用",
    "Leathercase": "门户产品",
    "Light Loading Performance": "性能",
    "LiveWallpaper": "桌面产品",
    "Lock screen": "门户产品",
    "Lockscreen": "门户产品",
    "LowPower": "续航温升",
    "LowPower_tOS": "续航温升",
    "MOL": "基础服务",
    "MagazineService": "桌面产品",
    "MemoryManage": "性能",
    "Messages": "通信",
    "MicroIntelligence": "系统应用",
    "MobileCloner": "创新产品",
    "NFC": "AIOT",
    "NFC-Settings": "AIOT",
    "NavigationBar": "门户产品",
    "Network": "通信",
    "Notes": "创新产品",
    "Notification": "门户产品",
    "OOBE": "门户产品",
    "OSSettingsExt": "门户产品",
    "OScloud": "基础服务",
    "OTA": "OTA",
    "OTALab": "OTA",
    "One-Tap Button": "框架应用",
    "One-handed Mode": "框架应用",
    "PCConnect": "AIOT",
    "PalmStore": "三方",
    "Phoenix": "三方",
    "PhoneMaster": "基础服务",
    "PictureInPicture": "框架应用",
    "PrivacyPassword": "系统应用",
    "Questionnaire": "基础服务",
    "Questionnaire/Feedback": "基础服务",
    "QuickCenter": "门户产品",
    "Reboot": "稳定性",
    "RecentApp": "桌面产品",
    "RecentAPP": "桌面产品",
    "Removable special": "系统应用",
    "SIM Card": "通信",
    "SPD": "翻译测试组",
    "STK": "通信",
    "ScreenRecord": "门户产品",
    "ScreenShot": "门户产品",
    "SecondaryHome": "门户产品",
    "Settings": "系统应用",
    "Settings_Search": "系统应用",
    "Settings_Translation": "翻译测试组",
    "ShareVia": "框架应用",
    "Sharevia": "框架应用",
    "Shutdowninterface": "门户产品",
    "Smart Assistant": "桌面产品",
    "Smart Hub": "框架应用",
    "Smart Panel": "框架应用",
    "SmartMessage": "基础服务",
    "SmartPanel": "框架应用",
    "SmartScanner": "创新产品",
    "Social Turbo": "框架应用",
    "SoundPicker": "音视频",
    "SoundRecorder": "创新产品",
    "SplitScreen": "框架应用",
    "StatusBar": "门户产品",
    "TP_Effect": "器件",
    "Telephone Supplyment Service": "通信",
    "Telephony": "通信",
    "Theme": "创新产品",
    "ThunderBack": "框架应用",
    "Thunderback": "框架应用",
    "TikTok Lite": "三方",
    "TransAtomicCore": "门户产品",
    "TransFind": "基础服务",
    "TransID": "基础服务",
    "TranssionStylus": "框架应用",
    "TranssionTips": "创新产品",
    "UI_UX_UE": "桌面产品",
    "Video Codec": "音视频",
    "Video assistant": "框架应用",
    "Vishaplayer": "创新产品",
    "Visha\Visha player": "创新产品",
    "Volume dialog": "门户产品",
    "WIFI": "AIOT",
    "WIFI-Settings": "AIOT",
    "WallpaperPicker": "桌面产品",
    "Weather": "创新产品",
    "Widevine L1": "音视频",
    "XOS/HIOS/Itle Launcher": "桌面产品",
    "XOSLauncher": "桌面产品",
    "Xhide": "系统应用",
    "Za-Hooc": "系统应用",
    "notification": "门户产品",
    "subSystemUI": "门户产品",
    "teleSettings": "通信",
    "zeroscreen": "桌面产品",
    "对应模块悬停问题提交自己模块": "框架应用",
    "对应的应用/系统": "系统应用",
    "暂无": "框架应用",
    "系统开发部-项目适配": "桌面产品",
    "销量统计": "系统应用",
    "Freezer": "系统应用",
    "Visha\\Visha player": "创新产品",
}

# 子模块名 → 业务领域（当Jira模块名为空时回退）
SUBMODULE_TO_DOMAIN = {
    "AI Gallery": "敏捷测试",
    "AI Writing": "框架应用",
    "AI efficiency": "框架应用",
    "AICalculator": "敏捷测试",
    "AICoreModelManager": "基础服务",
    "AITips": "桌面产品",
    "AOD (含趣味外屏)": "门户产品",
    "Applock": "系统应用",
    "BackLight": "系统应用",
    "BackLight1.0": "系统应用",
    "BackupAnd Restore": "系统应用",
    "Calculator": "创新产品",
    "Calendar": "日历",
    "Charginganimation": "门户产品",
    "Childmode": "系统应用",
    "Clipper": "敏捷测试",
    "Clipper-Oneshot": "敏捷测试",
    "Clock": "创新产品",
    "CutePet": "桌面产品",
    "DemoMode": "基础服务",
    "DesktopLayout": "桌面产品",
    "DesktopSettings": "桌面产品",
    "DragDrop": "框架应用",
    "DualApp": "系统应用",
    "Dynamic Color": "框架应用",
    "DynamicBar": "门户产品",
    "DynamicWallpaper": "桌面产品",
    "Ella": "基础服务",
    "Ella识屏": "基础服务",
    "Ewarrantycard": "基础服务",
    "Externalscreensuggestion": "桌面产品",
    "FMRadio": "敏捷测试",
    "FW_DualSystem": "系统应用",
    "Feedback": "基础服务",
    "FileManager": "创新产品",
    "Finder": "基础服务",
    "Flex-Still Mode": "框架应用",
    "Flipmusic": "敏捷测试",
    "Foldable_compatibility": "框架应用",
    "Font": "框架应用",
    "Full Scene Light": "系统应用",
    "Gesture Navigation": "门户产品",
    "GlobalSearch": "桌面产品",
    "GlobalTheme": "桌面产品",
    "Google Accessibility": "系统应用",
    "Google Android Auto": "系统应用",
    "Google Circle to Search": "系统应用",
    "Google Downloads": "系统应用",
    "Google InstallAPK": "系统应用",
    "Google NearByShare": "系统应用",
    "Google PIP": "框架应用",
    "Google Passkeys": "系统应用",
    "Google Settings": "系统应用",
    "Google Talkback": "系统应用",
    "GoogleContact": "基础服务",
    "GoogleMessage": "基础服务",
    "GooglePhone": "基础服务",
    "GoogleSwitch": "敏捷测试",
    "Headsetcontrol": "系统应用",
    "Indicator Light": "系统应用",
    "InfinixID": "基础服务",
    "LED": "系统应用",
    "Leathercase": "门户产品",
    "LiveWallpaper": "桌面产品",
    "Lockscreen": "门户产品",
    "LockscreenSetting": "门户产品",
    "MOL": "基础服务",
    "MagazineService": "桌面产品",
    "MicroIntelligence": "系统应用",
    "MobileCloner": "创新产品",
    "Multi User": "系统应用",
    "Notes": "创新产品",
    "Notification": "门户产品",
    "NotificationSetting": "门户产品",
    "OOBE": "门户产品",
    "OScloud": "基础服务",
    "One-Tap Button": "框架应用",
    "One-handed Mode": "框架应用",
    "Phone Master": "基础服务",
    "PrivacyPassword": "系统应用",
    "Questionnaire": "基础服务",
    "QuickCenter": "门户产品",
    "Recent": "桌面产品",
    "Recorder": "创新产品",
    "Removable special": "系统应用",
    "RepairMode": "系统应用",
    "SalesStatistics": "系统应用",
    "Screen Relay": "框架应用",
    "ScreenRecord": "门户产品",
    "ScreenShot": "门户产品",
    "SecondaryHome": "门户产品",
    "Settings": "系统应用",
    "Sharevia": "框架应用",
    "Shutdowninterface": "门户产品",
    "Smart Hub": "框架应用",
    "Smart Panel": "框架应用",
    "SmartMessage": "基础服务",
    "SmartScanner": "创新产品",
    "SmartScene": "桌面产品",
    "Social Turbo": "框架应用",
    "SplitScreen": "框架应用",
    "StatusBar": "门户产品",
    "TPMS": "基础服务",
    "Tent Mode": "框架应用",
    "Theme": "创新产品",
    "Thunderback": "框架应用",
    "Tips": "创新产品",
    "TransAtomicCore": "门户产品",
    "TransFind": "基础服务",
    "TranssionStylus": "框架应用",
    "Video Assistant": "框架应用",
    "Vishaplayer": "创新产品",
    "Volume dialog": "门户产品",
    "WallpaperPicker": "桌面产品",
    "Water Drop Screen": "系统应用",
    "Wear": "桌面产品",
    "Weather": "创新产品",
    "Works with": "框架应用",
    "Xhide|Vault|Hide": "系统应用",
    "Za-Hooc": "系统应用",
    "ZeroScreen": "桌面产品",
    "global taskbar": "桌面产品",
    "subSystemUI": "门户产品",
    "云空间": "基础服务",
    "全局引导": "创新产品",
    "桌面产品（全局主题）": "桌面产品",
    "SmartMessage（智能短信）": "基础服务",
}


def lookup_domain(module_name, sub_components=None):
    """根据模块名查找业务领域，支持多级回退

    Args:
        module_name: Jira模块名或component名
        sub_components: 子模块列表（用于二次匹配）

    Returns:
        str: 业务领域，未找到返回None
    """
    if not module_name:
        return None

    # 精确匹配
    if module_name in MODULE_TO_DOMAIN:
        return MODULE_TO_DOMAIN[module_name]

    # 子模块名匹配
    if module_name in SUBMODULE_TO_DOMAIN:
        return SUBMODULE_TO_DOMAIN[module_name]

    # 模糊匹配：取逗号分隔的第一个
    parts = module_name.split(",")
    first = parts[0].strip()
    if first in MODULE_TO_DOMAIN:
        return MODULE_TO_DOMAIN[first]

    # 关键词匹配
    for keyword, domain in MODULE_TO_DOMAIN.items():
        if keyword.lower() in module_name.lower() or module_name.lower() in keyword.lower():
            return domain

    # 如果传入子模块列表，逐个尝试
    if sub_components:
        for sub in sub_components:
            sub = sub.strip()
            if sub in SUBMODULE_TO_DOMAIN:
                return SUBMODULE_TO_DOMAIN[sub]
            if sub in MODULE_TO_DOMAIN:
                return MODULE_TO_DOMAIN[sub]

    return None
